# Generated by Django 5.1.7 on 2025-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SHOP ALL', 'Shop All'), ('T-SHIRTS', 'T-Shirts'), ('SHIRTS', 'Shirts'), ('SWEATERS', 'Sweaters'), ('FLEECE', 'Fleece'), ('TRUNKS', 'Trunks'), ('WALK SHORTS', 'Walk Shorts'), ('PANTS', 'Pants'), ('HEADWEAR', 'Headwear'), ('BIKINIS', 'Bikinis')], default='T-SHIRTS', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
